### ISSUE TITLE
NO traning and testing datasets available

### ISSUE THREAD

**Issue by sherkinglee** [Yang-J-LIN/lncLocator2#2]
Hi, 
I noticed the webserver of LncLocator2 is not available yet, and I tried to use "python main.py" running on my local computer. However, there were no "CNRCI" and "datasets" available in your Github repository.  I was wondering how long will LncLocator2 be ready for users to use?

Thanks,
Sherking

**Comment by Yang-J-LIN** [comment]
Hi,

Thanks for your interest in lncLocator. The server is under maintenance now and it will be finished by the end of this week. So you should be able to use it next week. The datasets are also stored on the server and you can download them from our website once the maintenance is finished.

Best

Yang

**Comment by sherkinglee** [comment]
Hi Yang,
Thanks very much! I also noticed that the webserver of lncLocator1 did not have a function to download the predicated results, so it would be much more friendly if lncLocator2 has this download function.

best wishes,
Sherking
